# Generated by Django 2.2.6 on 2019-11-04 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=1000)),
                ('precio', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=1000)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_compra', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tiene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pamedicinas.Medicina')),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pamedicinas.Notificacion')),
            ],
        ),
        migrations.AddField(
            model_name='notificacion',
            name='medicinas',
            field=models.ManyToManyField(through='pamedicinas.Tiene', to='pamedicinas.Medicina'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
